language: php

php:
    - 7.4
    - 8.0
    - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
    - composer update $PREFER_LOWEST

script:
    - php vendor/bin/simple-phpunit --debug

notifications:
    email: false
